#!/bin/bash

---
- hosts: localhost
  gather_facts: false
  vars_files:
    - /opt/seedbox/variables/account.yml
  tasks:
        
    # FACTS #######################################################################

    - name: create jackett state
      shell: |
        echo "1" > /opt/seedbox/status/jackett

    - name: Checking for existing app data
      stat:
        path: '/opt/seedbox/docker/{{user.name}}/authelia/configuration.yml'
      register: check

    - name: "Variables | Set 'cloudflare_enabled' variable"
      set_fact:
        cloudflare_enabled: "{{ true if not(
            (cloudflare.login is undefined)
            or
            (cloudflare.login is none)
            or
            (cloudflare.login | trim | length == 0)
            or
            (cloudflare.api is undefined)
            or
            (cloudflare.api is none)
            or
            (cloudflare.api | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'oauth_enabled' variable"
      set_fact:
        oauth_enabled: "{{ true if not(
            (oauth.client is undefined)
            or
            (oauth.client is none)
            or
            (oauth.client | trim | length == 0)
            or
            (oauth.secret is undefined)
            or
            (oauth.secret is none)
            or
            (oauth.secret | trim | length == 0)
            or
            (oauth.account is undefined)
            or
            (oauth.account is none)
            or
            (oauth.account | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'sub' variable"
      set_fact:
        sub_enabled: "{{ true if not(
            (sub.jackett is undefined)
            or
            (sub.jackett is none)
            or
            (sub.jackett | trim | length == 0)
          )
            else false }}"

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: "{{sub.jackett if sub_enabled else 'jackett'}}"
      when: cloudflare_enabled

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'jackett'
        intport: '9117'
        image: 'linuxserver/jackett'

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner={{user.userid}} group={{user.groupid}}'
      with_items:
        - '/opt/seedbox/docker/{{user.name}}/{{pgrole}}'

    # MIGRATIONS (MANDATORY) ############################################################
    - name: Checking for old app data
      stat:
        path: '/opt/seedbox/docker/{{user.name}}/{{pgrole}}/Jackett/ServerConfig.json'
      register: olddatacheck

    - name: Migrating appdata
      shell: 'mv /opt/seedbox/docker/{{user.name}}/{{pgrole}}/Jackett/* /opt/seedbox/docker/{{user.name}}/{{pgrole}}'
      ignore_errors: yes
      when: olddatacheck.stat.exists

    - name: Migrating appdata
      shell: 'rmdir /opt/seedbox/docker/{{user.name}}/{{pgrole}}/Jackett'
      ignore_errors: yes
      when: olddatacheck.stat.exists

    - name: Checking for existing app data
      stat:
        path: '/opt/seedbox/docker/{{user.name}}/{{pgrole}}/ServerConfig.json'
      register: datacheck

    # LABELS ######################################################################
    - name: 'Ajout label traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          ## HTTP Routers
          traefik.http.routers.jackett-rtr.entrypoints: 'https'
          traefik.http.routers.jackett-rtr.rule: 'Host(`{{sub.jackett if sub_enabled else pgrole}}.{{user.domain}}`)'
          traefik.http.routers.jackett-rtr.tls: 'true'
          ## Middlewares
          traefik.http.routers.jackett-rtr.middlewares: "{{ 'chain-authelia@file' if check.stat.exists | default(false) else 'chain-oauth@file' if oauth_enabled | default(false) else 'chain-basic-auth@file' }}"
          ## HTTP Services
          traefik.http.routers.jackett-rtr.service: 'jackett-svc'
          traefik.http.services.jackett-svc.loadbalancer.server.port: '9117'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/seedbox/docker/{{user.name}}/{{pgrole}}:/config/Jackett'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '{{user.userid}}'
          PGID: '{{user.groupid}}'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'

    # CONFIGURATION ####################################################
    - name: 'Waiting for {{pgrole}} to initialize'
      wait_for:
        path: '/opt/seedbox/docker/{{user.name}}/{{pgrole}}/ServerConfig.json'
        state: present
        msg: ServerConfig.json creation failed

    - name: 'Stopping {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        state: stopped

    - name: Restart {{pgrole}}
      docker_container:
        name: '{{pgrole}}'
        state: started

    - name: add resume file
      shell: |
        echo "{{pgrole}}-{{sub.jackett if sub_enabled else pgrole}}.{{user.domain}}" >> /opt/temp.txt

    - name: create jackett state
      shell: |
        echo "2" > /opt/seedbox/status/jackett


