
---
- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: mail
      prompt: "Votre adresse mail"
      private: no
    - name: password
      prompt: "Mot de passe de votre compte mail"
      private: no
    - name: smtp
      prompt: "Entrer le nom du serveur smtp"
      private: no
    - name: mattermost_port
      prompt: "Entrer le port du serveur smtp"
      private: no
  vars_files:
    - /opt/seedbox/variables/account.yml
  tasks:
        
    # FACTS #######################################################################

    - name: create mattermost state
      shell: |
        echo "1" > /opt/seedbox/status/mattermost

    - name: Checking for existing app data
      stat:
        path: '/opt/seedbox/docker/{{user.name}}/authelia/configuration.yml'
      register: check

    - name: "Variables | Set 'cloudflare_enabled' variable"
      set_fact:
        cloudflare_enabled: "{{ true if not(
            (cloudflare.login is undefined)
            or
            (cloudflare.login is none)
            or
            (cloudflare.login | trim | length == 0)
            or
            (cloudflare.api is undefined)
            or
            (cloudflare.api is none)
            or
            (cloudflare.api | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'oauth_enabled' variable"
      set_fact:
        oauth_enabled: "{{ true if not(
            (oauth.client is undefined)
            or
            (oauth.client is none)
            or
            (oauth.client | trim | length == 0)
            or
            (oauth.secret is undefined)
            or
            (oauth.secret is none)
            or
            (oauth.secret | trim | length == 0)
            or
            (oauth.account is undefined)
            or
            (oauth.account is none)
            or
            (oauth.account | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'sub' variable"
      set_fact:
        sub_enabled: "{{ true if not(
            (sub.mattermost is undefined)
            or
            (sub.mattermost is none)
            or
            (sub.mattermost | trim | length == 0)
          )
            else false }}"

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: "{{sub.mattermost if sub_enabled else 'mattermost'}}"
      when: cloudflare_enabled

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'mattermost'

    - name: Creating  paths
      file: 'path={{item}} state=directory mode=0775'
      with_items:
        - '/opt/seedbox/docker/{{user.name}}/{{pgrole}}/data'
        - '/opt/seedbox/docker/{{user.name}}/{{pgrole}}/logs'
        - '/opt/seedbox/docker/{{user.name}}/{{pgrole}}/config'
        - '/opt/seedbox/docker/{{user.name}}/{{pgrole}}/plugins'
        - '/opt/seedbox/docker/{{user.name}}/{{pgrole}}/client-plugins'
        - '/opt/seedbox/docker/{{user.name}}/{{pgrole}}/db'

    - name: permissions
      shell: |
        sudo chown -R 2000:2000 /opt/seedbox/docker/{{user.name}}/mattermost

    - name: Import docker-compose.yml
      template:
        src: /opt/seedbox-compose/includes/dockerapps/templates/mattermost/mattermost.yml.j2
        dest: /tmp/mattermost-docker/mattermost.yml

    - name: Import config.json
      template:
        src: /opt/seedbox-compose/includes/dockerapps/templates/mattermost/config.json.j2
        dest: /opt/seedbox/docker/{{user.name}}/{{pgrole}}/config/config.json

    - name: docker compose up -d
      command: docker-compose -f /tmp/mattermost-docker/mattermost.yml up -d

    - name: add resume file
      shell: |
        echo "{{pgrole}}-{{sub.mattermost if sub_enabled else pgrole}}.{{user.domain}}" >> /opt/temp.txt

    - name: create mattermost state
      shell: |
        echo "2" > /opt/seedbox/status/mattermost

