#!/bin/bash

---
- hosts: localhost
  gather_facts: false
  vars_files:
    - /opt/seedbox/variables/account.yml
  tasks:
        
    # FACTS #######################################################################

    - name: create mellow state
      shell: |
        echo "1" > /opt/seedbox/status/mellow

    - name: Checking for existing app data
      stat:
        path: '/opt/seedbox/docker/{{user.name}}/authelia/configuration.yml'
      register: check

    - name: "Variables | Set 'cloudflare_enabled' variable"
      set_fact:
        cloudflare_enabled: "{{ true if not(
            (cloudflare.login is undefined)
            or
            (cloudflare.login is none)
            or
            (cloudflare.login | trim | length == 0)
            or
            (cloudflare.api is undefined)
            or
            (cloudflare.api is none)
            or
            (cloudflare.api | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'oauth_enabled' variable"
      set_fact:
        oauth_enabled: "{{ true if not(
            (oauth.client is undefined)
            or
            (oauth.client is none)
            or
            (oauth.client | trim | length == 0)
            or
            (oauth.secret is undefined)
            or
            (oauth.secret is none)
            or
            (oauth.secret | trim | length == 0)
            or
            (oauth.account is undefined)
            or
            (oauth.account is none)
            or
            (oauth.account | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'sub' variable"
      set_fact:
        sub_enabled: "{{ true if not(
            (sub.mellow is undefined)
            or
            (sub.mellow is none)
            or
            (sub.mellow | trim | length == 0)
          )
            else false }}"

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: "{{sub.mellow if sub_enabled else 'mellow'}}"
      when: cloudflare_enabled

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner={{user.userid}} group={{user.groupid}}'
      with_items:
        - '/opt/seedbox/docker/{{user.name}}/mellow'

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'mellow'
        intport: '5060'
        image: 'voidp/mellow'

    - name: 'Ajout label traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          ## HTTP Routers
          traefik.http.routers.mellow-rtr.entrypoints: 'https'
          traefik.http.routers.mellow-rtr.rule: 'Host(`{{sub.mellow if sub_enabled else pgrole}}.{{user.domain}}`)'
          traefik.http.routers.mellow-rtr.tls: 'true'
          ## Middlewares
          traefik.http.routers.mellow-rtr.middlewares: "{{ 'chain-authelia@file' if check.stat.exists | default(false) else 'chain-oauth@file' if oauth_enabled | default(false) else 'chain-basic-auth@file' }}"
          ## HTTP Services
          traefik.http.routers.mellow-rtr.service: 'mellow-svc'
          traefik.http.services.mellow-svc.loadbalancer.server.port: '5060'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/seedbox/docker/{{user.name}}/mellow:/usr/src/app/data/'

    - name: 'Deploying mellow'
      docker_container:
        name: 'mellow'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'

    - name: add resume file
      shell: |
        echo "{{pgrole}}-{{sub.mellow if sub_enabled else pgrole}}.{{user.domain}}" >> /opt/temp.txt

    - name: create mellow state
      shell: |
        echo "2" > /opt/seedbox/status/mellow


