#!/bin/bash

---
- hosts: localhost
  gather_facts: false
  vars_files:
    - /opt/seedbox/variables/account.yml
  tasks:
        
    # FACTS #######################################################################

    - name: create portainer state
      shell: |
        echo "1" > /opt/seedbox/status/portainer

    - name: Checking for existing app data
      stat:
        path: '/opt/seedbox/docker/{{user.name}}/authelia/configuration.yml'
      register: check

    - name: "Variables | Set 'cloudflare_enabled' variable"
      set_fact:
        cloudflare_enabled: "{{ true if not(
            (cloudflare.login is undefined)
            or
            (cloudflare.login is none)
            or
            (cloudflare.login | trim | length == 0)
            or
            (cloudflare.api is undefined)
            or
            (cloudflare.api is none)
            or
            (cloudflare.api | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'oauth_enabled' variable"
      set_fact:
        oauth_enabled: "{{ true if not(
            (oauth.client is undefined)
            or
            (oauth.client is none)
            or
            (oauth.client | trim | length == 0)
            or
            (oauth.secret is undefined)
            or
            (oauth.secret is none)
            or
            (oauth.secret | trim | length == 0)
            or
            (oauth.account is undefined)
            or
            (oauth.account is none)
            or
            (oauth.account | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'sub' variable"
      set_fact:
        sub_enabled: "{{ true if not(
            (sub.portainer is undefined)
            or
            (sub.portainer is none)
            or
            (sub.portainer | trim | length == 0)
          )
            else false }}"

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: "{{sub.portainer if sub_enabled else 'portainer'}}"
      when: cloudflare_enabled

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'portainer'
        intport: '9000'
        image: 'portainer/portainer'

    # LABELS ######################################################################
    - name: 'Ajout label traefik'
      set_fact:
        labels:
          traefik.enable: 'true'
          ## HTTP Routers
          traefik.http.routers.portainer-rtr.entrypoints: 'https'
          traefik.http.routers.portainer-rtr.rule: 'Host(`{{sub.portainer if sub_enabled else pgrole}}.{{user.domain}}`)'
          traefik.http.routers.portainer-rtr.tls: 'true'
          ## Middlewares
          #traefik.http.routers.portainer-rtr.middlewares: "{{ 'chain-oauth@file' if oauth_enabled | default(false) else 'chain-basic-auth@file' }}"
          ## HTTP Services
          traefik.http.routers.portainer-rtr.service: 'portainer-svc'
          traefik.http.services.portainer-svc.loadbalancer.server.port: '9000'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/seedbox/docker/{{pgrole}}:/data'
          - '/var/run/docker.sock:/var/run/docker.sock'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '0'
          PGID: '0'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{labels}}'

    - name: add resume file
      shell: |
        echo "{{pgrole}}-{{sub.portainer if sub_enabled else pgrole}}.{{user.domain}}" >> /opt/temp.txt

    - name: create portainer state
      shell: |
        echo "2" > /opt/seedbox/status/portainer


