#!/bin/bash

---
- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: enabled
      prompt: "VPN_ENABLED (yes ou no)"
      private: no
    - name: type
      prompt: "VPN_TYPE (wireguard ou openvpn)"
      private: no
    - name: username
      prompt: "VPN_USERNAME"
      private: no
    - name: password
      prompt: "VPN_PASSWORD"
      private: no
    - name: network
      prompt: "LAN_NETWORK (ex 172.18.0.0/24)"
      private: no
  vars_files:
    - /opt/seedbox/variables/account.yml
  tasks:

    # FACTS #######################################################################

    - name: create qbitorrentvpn state
      shell: |
        echo "1" > /opt/seedbox/status/qbitorrentvpn

    - name: Checking for existing app data
      stat:
        path: '/opt/seedbox/docker/{{user.name}}/authelia/configuration.yml'
      register: check
  
    - name: "Variables | Set 'cloudflare_enabled' variable"
      set_fact:
        cloudflare_enabled: "{{ true if not(
            (cloudflare.login is undefined)
            or
            (cloudflare.login is none)
            or
            (cloudflare.login | trim | length == 0)
            or
            (cloudflare.api is undefined)
            or
            (cloudflare.api is none)
            or
            (cloudflare.api | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'oauth_enabled' variable"
      set_fact:
        oauth_enabled: "{{ true if not(
            (oauth.client is undefined)
            or
            (oauth.client is none)
            or
            (oauth.client | trim | length == 0)
            or
            (oauth.secret is undefined)
            or
            (oauth.secret is none)
            or
            (oauth.secret | trim | length == 0)
            or
            (oauth.account is undefined)
            or
            (oauth.account is none)
            or
            (oauth.account | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'sub' variable"
      set_fact:
        sub_enabled: "{{ true if not(
            (sub.qbitorrentvpn is undefined)
            or
            (sub.qbitorrentvpn is none)
            or
            (sub.qbitorrentvpn | trim | length == 0)
          )
            else false }}"

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: "{{sub.qbitorrentvpn if sub_enabled else 'qbitorrentvpn'}}"
      when: cloudflare_enabled

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'qbitorrentvpn'
        intport: '8080'
        image: 'dyonr/qbittorrentvpn:latest'

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner={{user.userid}} group={{user.groupid}}'
      with_items:
        - '/opt/seedbox/docker/{{user.name}}/{{pgrole}}'

    # LABELS ######################################################################
    - name: 'Ajout label traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          ## HTTP Routers
          traefik.http.routers.qbitorrentvpn-rtr.entrypoints: 'https'
          traefik.http.routers.qbitorrentvpn-rtr.rule: 'Host(`{{sub.qbitorrentvpn if sub_enabled else pgrole}}.{{user.domain}}`)'
          traefik.http.routers.qbitorrentvpn-rtr.tls: 'true'
          ## Middlewares
          traefik.http.routers.qbitorrentvpn-rtr.middlewares: "{{ 'chain-authelia@file' if check.stat.exists | default(false) else 'chain-oauth@file' if oauth_enabled | default(false) else 'chain-basic-auth@file' }}"
          ## HTTP Services
          traefik.http.routers.qbitorrentvpn-rtr.service: 'qbitorrentvpn-svc'
          traefik.http.services.qbitorrentvpn-svc.loadbalancer.server.port: '8080'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/seedbox/docker/{{user.name}}/{{pgrole}}/config:/config'
          - '/home/{{user.name}}/local/{{pgrole}}/downloads:/downloads'
          - '/home/{{user.name}}:/home/{{user.name}}'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          PUID: '{{user.userid}}'
          PGID: '{{user.groupid}}'
          VPN_ENABLED: '{{enabled}}'
          VPN_TYPE: '{{type}}'
          VPN_USERNAME: '{{username}}'
          VPN_PASSWORD: '{{password}}'
          LAN_NETWORK: '{{network}}'
          DISABLE_IPV6: 0
          TZ: 'Europe/Paris'

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        ports:
          - '8999:8999'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'

    - name: add resume file
      shell: |
        echo "{{pgrole}}-{{sub.qbitorrentvpn if sub_enabled else pgrole}}.{{user.domain}}" >> /opt/temp.txt

    - name: create qbitorrentvpn state
      shell: |
        echo "2" > /opt/seedbox/status/qbitorrentvpn
