#!/bin/bash

---
- hosts: localhost
  gather_facts: false
  vars_files:
    - /opt/seedbox/variables/account.yml
  tasks:
        
    # FACTS #######################################################################

    - name: create ubooquity state
      shell: |
        echo "1" > /opt/seedbox/status/ubooquity

    - name: Checking for existing app data
      stat:
        path: '/opt/seedbox/docker/{{user.name}}/authelia/configuration.yml'
      register: check

    - name: "Variables | Set 'cloudflare_enabled' variable"
      set_fact:
        cloudflare_enabled: "{{ true if not(
            (cloudflare.login is undefined)
            or
            (cloudflare.login is none)
            or
            (cloudflare.login | trim | length == 0)
            or
            (cloudflare.api is undefined)
            or
            (cloudflare.api is none)
            or
            (cloudflare.api | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'oauth_enabled' variable"
      set_fact:
        oauth_enabled: "{{ true if not(
            (oauth.client is undefined)
            or
            (oauth.client is none)
            or
            (oauth.client | trim | length == 0)
            or
            (oauth.secret is undefined)
            or
            (oauth.secret is none)
            or
            (oauth.secret | trim | length == 0)
            or
            (oauth.account is undefined)
            or
            (oauth.account is none)
            or
            (oauth.account | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'sub' variable"
      set_fact:
        sub_enabled: "{{ true if not(
            (sub.ubooquity is undefined)
            or
            (sub.ubooquity is none)
            or
            (sub.ubooquity | trim | length == 0)
          )
            else false }}"

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: "{{sub.ubooquity if sub_enabled else 'ubooquity'}}"
      when: cloudflare_enabled

    # FACTS #######################################################################
    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'ubooquity'
        image: 'ghcr.io/linuxserver/ubooquity'

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner={{user.userid}} group={{user.groupid}}'
      with_items:
        - '/opt/seedbox/docker/{{user.name}}/{{pgrole}}'

    # LABELS ######################################################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.http.routers.ubooquity-rtr.entrypoints: 'https'
          traefik.http.routers.ubooquity-rtr.rule: 'Host(`{{sub.ubooquity if sub_enabled else pgrole}}.{{user.domain}}`)'
          traefik.http.routers.ubooquity-rtr.service: 'ubooquity'
          traefik.http.services.ubooquity.loadbalancer.server.port: '2202'
          traefik.http.routers.ubooquity-admin-rtr.entrypoints: 'https'
          traefik.http.routers.ubooquity-admin-rtr.rule: 'Host(`{{sub.ubooquity if sub_enabled else pgrole}}.{{user.domain}}`) && PathPrefix(`/ubooquity/admin`)'
          traefik.http.routers.ubooquity-admin-rtr.service: 'ubooquity-admin'
          traefik.http.services.ubooquity-admin.loadbalancer.server.port: '2203'

    - name: 'Setting Volumes'
      set_fact:
        pg_volumes:
          - '/opt/seedbox/docker/{{user.name}}/{{pgrole}}:/config'
          - '/home/{{user.name}}:/home/{{user.name}}'
          - '/home/{{user.name}}:/media'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting ENV'
      set_fact:
        pg_env:
          PUID: '{{user.userid}}'
          PGID: '{{user.groupid}}'
          TZ: 'Europe/Paris'

    # MAIN DEPLOYMENT #############################################################
    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        hostname: 'library'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'

    - name: add resume file
      shell: |
        echo "{{pgrole}}-{{sub.ubooquity if sub_enabled else pgrole}}.{{user.domain}}" >> /opt/temp.txt

    - name: create ubooquity state
      shell: |
        echo "2" > /opt/seedbox/status/ubooquity


