#!/bin/bash

---
- hosts: localhost
  gather_facts: true
  vars_files:
    - /opt/seedbox/variables/account.yml
  tasks:
        
    # FACTS #######################################################################

    - name: create wetty state
      shell: |
        echo "1" > /opt/seedbox/status/wetty

    - name: Checking for existing app data
      stat:
        path: '/opt/seedbox/docker/{{user.name}}/authelia/configuration.yml'
      register: check

    - name: "Variables | Set 'cloudflare_enabled' variable"
      set_fact:
        cloudflare_enabled: "{{ true if not(
            (cloudflare.login is undefined)
            or
            (cloudflare.login is none)
            or
            (cloudflare.login | trim | length == 0)
            or
            (cloudflare.api is undefined)
            or
            (cloudflare.api is none)
            or
            (cloudflare.api | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'oauth_enabled' variable"
      set_fact:
        oauth_enabled: "{{ true if not(
            (oauth.client is undefined)
            or
            (oauth.client is none)
            or
            (oauth.client | trim | length == 0)
            or
            (oauth.secret is undefined)
            or
            (oauth.secret is none)
            or
            (oauth.secret | trim | length == 0)
            or
            (oauth.account is undefined)
            or
            (oauth.account is none)
            or
            (oauth.account | trim | length == 0)
          )
            else false }}"

    - name: "Variables | Set 'sub' variable"
      set_fact:
        sub_enabled: "{{ true if not(
            (sub.wetty is undefined)
            or
            (sub.wetty is none)
            or
            (sub.wetty | trim | length == 0)
          )
            else false }}"

    - name: Get Public IP Address
      shell: dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com | awk -F'\"' '{ print $2}'
      register: public_ip_lookup

    - name: "Set DNS Record on CloudFlare"
      include_tasks: '/opt/seedbox-compose/includes/config/roles/cloudflare/tasks/main.yml'
      vars:
        subdomain: "{{sub.wetty if sub_enabled else 'wetty'}}"
      when: cloudflare_enabled

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'wetty'
        intport: '3000'
        image: 'svenihoney/wetty:latest'

    - name: Creating paths
      file: 'path={{item}} state=directory mode=0775 owner={{user.userid}} group={{user.groupid}}'
      with_items:
        - '/opt/seedbox/docker/{{user.name}}/{{pgrole}}'

    # LABELS ######################################################################
    - name: 'Ajout label traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          ## HTTP Routers
          traefik.http.routers.wetty-rtr.entrypoints: 'https'
          traefik.http.routers.wetty-rtr.rule: 'Host(`{{sub.wetty if sub_enabled else pgrole}}.{{user.domain}}`)'
          traefik.http.routers.wetty-rtr.tls: 'true'
          ## Middlewares
          traefik.http.routers.wetty-rtr.middlewares: "{{ 'chain-authelia@file' if check.stat.exists | default(false) else 'chain-oauth@file' if oauth_enabled | default(false) else 'chain-basic-auth@file' }}"
          ## HTTP Services
          traefik.http.routers.wetty-rtr.service: 'wetty-svc'
          traefik.http.services.wetty-svc.loadbalancer.server.port: '3000'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          VIRTUAL_HOST: 'wetty.{{user.domain}}'
          VIRTUAL_PORT: '3000'
          REMOTE_SSH_SERVER: '{{public_ip_lookup.stdout}}'
          REMOTE_SSH_PORT: "{{ ansible_env['SSH_CLIENT'].split() | last }}"
          REMOTE_SSH_USER: ''

    # MAIN DEPLOYMENT #############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: traefik_proxy
        state: started
        labels: '{{pg_labels}}'

    - name: add resume file
      shell: |
        echo "{{pgrole}}-{{sub.wetty if sub_enabled else pgrole}}.{{user.domain}}" >> /opt/temp.txt

    - name: create wetty state
      shell: |
        echo "2" > /opt/seedbox/status/wetty


